### ISSUE TITLE
Zatca 2nd phase

### ISSUE THREAD

**Issue by OmarHarbi** [Evincible-Solutions/EvsZatcaQRCodeString#1]
Please help us in Zatca 2nd phase 
Your help will be highly appreciated.
Thank you very much.

**Comment by Harisul44** [comment]
Yes, We need help for Zatca 2nd Phase .

**Comment by fasilmarshooq** [comment]
Hi All,
Whoever is interested in phase 2 please refer https://github.com/azep-engineering/ZatcaHelper , and watch out for the repo we will slowly make the rest of the features open source, if you want access to our full repo please write to us at sales@dev-bee.com.

**Comment by Umarali33** [comment]
> Please help us in Zatca 2nd phase Your help will be highly appreciated. Thank you very much.

Hi Omar,

Here is our Zatca Phase 2 API Documentation
[API Doc](https://zatcaapidocs.evinciblesolutions.com/reference/api-reference)

For More Information
[Contact Us](https://evinciblesolutions.com/e-invoicing/)

We have 30+ Clients in all our KSA who live and use our Zatca Phase 2 solutions.

**Comment by Umarali33** [comment]
> Yes, We need help for Zatca 2nd Phase .

Hi Harisul,

Here is our Zatca Phase 2 API Documentation
[API Doc](https://zatcaapidocs.evinciblesolutions.com/reference/api-reference)

For More Information
[Contact Us](https://evinciblesolutions.com/e-invoicing/)

We have 30+ Clients in all our KSA who live and use our Zatca Phase 2 solutions.
